# Use a imagem base do Ubuntu
FROM ubuntu:latest

# Instale dependências básicas e PHP
RUN apt-get update && apt-get install -y \
    software-properties-common \
    lsb-release \
    apt-transport-https \
    ca-certificates \
    wget \
    php \
    php-cli \
    php-mbstring \
    php-xml \
    php-zip \
    php-sqlite3